# A Workflow is an automated process defined in a YAML file that tells GitHub Actions what tasks to perform.

name: EC2 pipeline

on:  # An Event is an action that starts (triggers) the workflow.
  push: # When someone pushes code to the main branch, start this workflow.
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"

jobs:  # A Job is a group of steps that execute together on a runner.
  terraform:
    runs-on: ubuntu-22.04  # A Runner is the machine/server where GitHub Actions executes your jobs.

    steps: # A Step is an individual task inside a job.
      - name: checkout folder
        uses: actions/checkout@v4

      - name: authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_1 }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        run: terraform init
        working-directory: environment/dev
        
      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: environment/dev
     
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: environment/dev
